version: "3"

services:
  wsify:
    build: ./wsify
    ports:
      - 8080:4040
    command: wsify -webhook=http://fastapi/check -debug
    container_name: wsify
    depends_on:
      - fastapi

  web:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ".:/usr/share/nginx/html"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    depends_on:
      - wsify

  pusher:
    depends_on:
      - wsify
    build: .

  fastapi:
    build: ./checker
    command: "uvicorn main:app --host 0.0.0.0 --port 80"
    ports:
      - 8000:80